services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432

    volumes:
      - db_data:/var/lib/postgresql/data  # Monte le volume persistant pour la base de données

    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: currency
    
    networks:
      - app_network


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
  

  
    


volumes:
  db_data:
    driver: local

networks:
  app_network:
