services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432

    volumes:
      - db_data:/var/lib/postgresql/data  # Monte le volume persistant pour la base de données

    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: currency
    
    networks:
      - app_network


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app_network
  

  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Monte le code source local dans le conteneur pour faciliter le développement
    depends_on:
      - db

    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://admin:example@db:5432/currency  # Connexion à la base de données
    
    networks:
      - app_network

# npm install react-scripts --save
    


volumes:
  db_data:
    driver: local

networks:
  app_network:
