version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432

    volumes:
      - db_data:/var/lib/postgresql/data  # Monte le volume persistant pour la base de données

    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: currency


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  db_data:
    driver: local
