# Generated by Django 5.1.3 on 2024-11-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devise',
            old_name='nom',
            new_name='pair',
        ),
        migrations.RenameField(
            model_name='devise',
            old_name='prix',
            new_name='ratio',
        ),
    ]
